import { Bot, Building2, Cable, CheckCircle2, MapPin, Route, ShieldCheck } from "lucide-react";

import { RobotCard } from "@/components/RobotCard";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { Robot } from "@/types/dashboard";

export function RobotOrchestration({ robots }: { robots: Robot[] }) {
  return <section className="space-y-5"><section className="flex flex-col justify-between gap-3 border-b border-slate-200 pb-5 sm:flex-row sm:items-end"><div><p className="section-kicker">Fleet orchestration</p><h2 className="mt-1 text-xl font-semibold tracking-tight">机器人能力与路线边界</h2><p className="mt-1 text-xs text-slate-500">面试演示使用 Mock Adapter；能力约束和调度评分仍由 Phase 3 的确定性引擎负责。</p></div><div className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={14} />Robot-first + Human Fallback</div></section><section className="grid gap-4 xl:grid-cols-3">{robots.map((robot) => <RobotCard key={robot.id} robot={robot} />)}</section><section className="grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><Card><CardHeader><p className="section-kicker">Mission playback</p><h3 className="mt-1 text-base font-semibold">跨楼栋任务的可讲解路径</h3></CardHeader><CardContent className="p-5 pt-3"><div className="relative overflow-hidden border border-slate-200 bg-[#f8fafb] p-5"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3 text-center text-xs"><div className="border border-slate-300 bg-white p-4"><Building2 size={16} className="mx-auto text-slate-500" /><p className="mt-2 font-semibold text-slate-700">B 栋 1F</p><p className="mt-1 text-[11px] text-slate-500">Robot C · 低噪室内任务</p></div><div className="flex flex-col items-center gap-2 text-slate-400"><Cable size={17} /><span className="text-[10px]">Elevator + Skybridge</span></div><div className="border border-slate-300 bg-white p-4"><MapPin size={16} className="mx-auto text-slate-500" /><p className="mt-2 font-semibold text-slate-700">A 栋 1F</p><p className="mt-1 text-[11px] text-slate-500">Camera → SLAM target</p></div></div><div className="mt-5 flex items-center justify-center gap-2 border-t border-slate-200 pt-4 text-xs text-slate-600"><Bot size={15} className="robot-marker text-teal-700" /><span>Robot C follows deterministic connectors; the UI never claims a real device moved.</span></div></div></CardContent></Card><Card><CardHeader><p className="section-kicker">Interview cues</p><h3 className="mt-1 text-base font-semibold">三句话讲清楚系统</h3></CardHeader><CardContent className="space-y-3 p-5 pt-3">{[["01", "先定位", "Camera 画面通过同一套 Phase 2 映射落到 SLAM 坐标。"], ["02", "再约束", "Capability Engine 先过滤不安全或不可达机器人。"], ["03", "后闭环", "调度、执行、验收和 Human Fallback 都可审计。"]].map(([index, title, detail]) => <div key={index} className="flex gap-3 border-b border-slate-100 pb-3 last:border-0"><span className="font-mono text-xs text-slate-400">{index}</span><div><p className="text-xs font-semibold text-slate-700">{title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{detail}</p></div></div>)}<p className="flex items-center gap-2 pt-1 text-xs text-emerald-700"><CheckCircle2 size={14} />可回到事件中心运行四类稳定 Scenario。</p></CardContent></Card></section></section>;
}
