import { useEffect, useRef, useState, type ReactNode } from "react";
import { AlertTriangle, Bot, CheckCircle2, ChevronRight, ClipboardCheck, LoaderCircle, MapPin, Play, Radio, Route, UserRound } from "lucide-react";

import { createMockEvent, fetchEventTemplates, fetchWorkflowEvent, runWorkflow } from "@/api/workflow";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { AssignmentCandidate, EventTemplate, WorkflowEvent } from "@/types/workflow";

export function WorkflowSchedulerPanel({ presentation = "dashboard" }: { presentation?: "dashboard" | "interview" }) {
  const [templates, setTemplates] = useState<EventTemplate[]>([]); const [selectedTemplate, setSelectedTemplate] = useState("heavy_spill"); const [event, setEvent] = useState<WorkflowEvent>();
  const [selectedCandidate, setSelectedCandidate] = useState<AssignmentCandidate>(); const [error, setError] = useState(""); const [running, setRunning] = useState(false); const [streamState, setStreamState] = useState("等待事件流");
  const activeEventId = useRef<string | undefined>(undefined);
  const refreshTimer = useRef<number | undefined>(undefined);
  useEffect(() => { fetchEventTemplates().then(setTemplates).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "无法加载 Mock 模板")); }, []);
  useEffect(() => { activeEventId.current = event?.event_id; }, [event?.event_id]);
  useEffect(() => {
    const source = new EventSource("/api/events/stream");
    source.addEventListener("workflow", (message) => { const update = JSON.parse((message as MessageEvent).data) as { event_id:string; state:string }; setStreamState(`SSE · ${update.state}`); if (activeEventId.current === update.event_id) { if (refreshTimer.current) window.clearTimeout(refreshTimer.current); refreshTimer.current = window.setTimeout(() => { void fetchWorkflowEvent(update.event_id).then(setEvent); }, 120); } });
    source.onerror = () => setStreamState("事件流重连中");
    return () => { source.close(); if (refreshTimer.current) window.clearTimeout(refreshTimer.current); };
  }, []);
  async function runMockWorkflow(template = selectedTemplate) { setRunning(true); setError(""); setSelectedCandidate(undefined); setSelectedTemplate(template); try { const created = await createMockEvent(template); const completed = await runWorkflow(created.event_id); setEvent(completed); setStreamState(`SSE · ${completed.state}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "工作流执行失败"); } finally { setRunning(false); } }
  return <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)]">
    <Card><CardHeader className="flex flex-col gap-3 p-5 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="section-kicker">Workflow + Scheduler</p><h2 className="mt-1 text-base font-semibold">{presentation === "interview" ? "四类 Scenario 讲解台" : "可解释自治闭环"}</h2><p className="mt-1 text-xs text-slate-500">确定性状态机、能力约束与评分；全部使用稳定 Mock 数据。</p></div><Badge variant="outline"><Radio size={11} className="mr-1" />{streamState}</Badge></CardHeader><CardContent className="p-5 pt-1">{presentation === "interview" && <ScenarioLauncher templates={templates} selectedTemplate={selectedTemplate} running={running} onLaunch={(template) => void runMockWorkflow(template)} />}<div className="flex flex-col gap-2 border-y border-slate-100 py-4 sm:flex-row"><select aria-label="Mock 事件模板" value={selectedTemplate} onChange={(next) => setSelectedTemplate(next.target.value)} className="h-9 min-w-0 flex-1 rounded-sm border border-slate-200 bg-white px-2 text-xs">{templates.map((template) => <option key={template.template} value={template.template}>{template.label}</option>)}</select><button onClick={() => void runMockWorkflow()} disabled={running || !templates.length} className="flex h-9 items-center justify-center gap-2 rounded-sm bg-slate-900 px-4 text-xs font-medium text-white hover:bg-slate-700 disabled:bg-slate-300">{running ? <LoaderCircle size={14} className="animate-spin" /> : <Play size={14} />}运行 Mock 闭环</button></div>{error && <p role="alert" className="mt-4 flex gap-2 border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><AlertTriangle size={15} />{error}</p>}{event ? <DecisionTrace event={event} /> : <div className="flex min-h-[225px] items-center justify-center border-b border-dashed border-slate-200 text-sm text-slate-400">选择一个稳定 Mock 事件，查看状态机和调度决策。</div>}</CardContent></Card>
    <div className="space-y-5">{event ? <><TaskProfile event={event} /><AssignmentPanel event={event} selectedCandidate={selectedCandidate} onSelect={setSelectedCandidate} /></> : <Card><CardContent className="p-6 text-sm text-slate-500">事件运行后将显示 Task Profile、候选机器人、评分与 Human Fallback 工单。</CardContent></Card>}</div>
  </section>;
}

function DecisionTrace({ event }: { event: WorkflowEvent }) { const states = event.transitions.filter((transition, index, transitions) => index === 0 || transition.state !== transitions[index - 1].state); return <div className="mt-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold text-slate-700">Decision Trace</p><Badge variant={event.state === "CLOSED" ? "success" : "warning"}>{event.state}</Badge></div><div className="flex max-h-[250px] flex-wrap gap-x-1 gap-y-2 overflow-y-auto pr-1">{states.map((transition, index) => <span key={transition.id} className="flex items-center gap-1"><span className={`rounded-sm border px-2 py-1 text-[11px] ${transition.state === "HUMAN_FALLBACK" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-slate-200 bg-slate-50 text-slate-700"}`}>{transition.state}</span>{index < states.length - 1 && <ChevronRight size={13} className="text-slate-300" />}</span>)}</div><div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-3"><TraceFact label="Camera" value={event.camera_id} /><TraceFact label="SLAM target" value={`${event.location.map_id} · ${event.location.x}, ${event.location.y}`} /><TraceFact label="Verification" value={event.verification?.result ?? "Pending"} /></div>{event.navigation_plan && <p className="mt-3 flex items-center gap-1.5 text-[11px] text-slate-500"><Route size={13} />{event.navigation_plan.display_path.join(" → ")}</p>}<MissionPlayback states={states.map((transition) => transition.state)} /><BeforeAfter event={event} /></div>; }
function TraceFact({ label, value }: { label:string; value:string }) { return <div><p className="section-kicker">{label}</p><p className="mt-1 truncate text-xs font-medium text-slate-700" title={value}>{value}</p></div>; }
function ScenarioLauncher({ templates, selectedTemplate, running, onLaunch }: { templates: EventTemplate[]; selectedTemplate: string; running: boolean; onLaunch: (template: string) => void }) { const cues: Record<string, string> = { outdoor_debris: "Robot A · 室外自主闭环", multiview_heavy_spill: "Robot B · 多视角重污", cross_building_debris: "Robot C · 电梯 + Skybridge", oversized_object: "Human Fallback · 能力边界" }; const scenarioOrder = ["outdoor_debris", "multiview_heavy_spill", "cross_building_debris", "oversized_object"]; return <div className="mb-4 grid gap-2 sm:grid-cols-2">{scenarioOrder.map((templateId) => templates.find((template) => template.template === templateId)).filter((template): template is EventTemplate => Boolean(template)).map((template, index) => <button key={template.template} onClick={() => onLaunch(template.template)} disabled={running} className={`group border p-3 text-left transition-colors ${template.template === selectedTemplate ? "border-slate-900 bg-slate-50" : "border-slate-200 hover:border-slate-400"}`}><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-slate-400">SCENARIO 0{index + 1}</span><Play size={13} className="text-slate-400 group-hover:text-slate-800" /></div><p className="mt-2 text-xs font-semibold text-slate-800">{template.label}</p><p className="mt-1 text-[11px] text-slate-500">{cues[template.template]}</p></button>)}</div>; }
function MissionPlayback({ states }: { states: string[] }) { const [active, setActive] = useState(0); useEffect(() => { setActive(0); if (states.length < 2) return undefined; const timer = window.setInterval(() => setActive((current) => current >= states.length - 1 ? current : current + 1), 420); return () => window.clearInterval(timer); }, [states.join("|")]); const hasElevator = states.some((state) => state === "WAITING_ELEVATOR" || state === "IN_ELEVATOR"); const hasSkybridge = states.includes("SKYBRIDGE"); return <div className="mt-4 border-t border-slate-100 pt-4"><div className="flex items-center justify-between"><p className="section-kicker">Mission playback</p><p className="text-[10px] text-slate-400">Mock 状态回放 · 非真实设备遥测</p></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><PlaybackSegment label="Robot path" active={active < states.length - 1} icon={<Bot size={14} className="robot-marker" />} detail="任务路由与执行" /><PlaybackSegment label="Elevator" active={hasElevator} icon={<span className={hasElevator ? "elevator-motion" : ""}>↕</span>} detail={hasElevator ? "连接器状态已审计" : "本任务无需电梯"} /><PlaybackSegment label="Skybridge" active={hasSkybridge} icon={<span className={hasSkybridge ? "skybridge-sweep" : ""}>→</span>} detail={hasSkybridge ? "跨楼栋连接已审计" : "本任务无需跨楼栋"} /></div><div className="mt-3 flex items-center gap-1 overflow-x-auto pb-1">{states.map((state, index) => <span key={`${state}-${index}`} className={`shrink-0 border px-1.5 py-1 font-mono text-[10px] ${index <= active ? "border-slate-500 bg-slate-800 text-white" : "border-slate-200 bg-white text-slate-400"}`}>{state}</span>)}</div></div>; }
function PlaybackSegment({ label, active, icon, detail }: { label: string; active: boolean; icon: ReactNode; detail: string }) { return <div className={`flex items-center gap-2 border p-2.5 ${active ? "border-slate-300 bg-slate-50" : "border-slate-100 text-slate-400"}`}><span className="flex h-6 w-6 items-center justify-center border border-slate-200 bg-white text-slate-600">{icon}</span><div><p className="text-[11px] font-semibold text-slate-700">{label}</p><p className="mt-0.5 text-[10px] text-slate-500">{detail}</p></div></div>; }
function BeforeAfter({ event }: { event: WorkflowEvent }) { return <div className="mt-4 grid gap-2 border-t border-slate-100 pt-4 sm:grid-cols-2"><div className="border border-slate-200 p-3"><p className="section-kicker">Before · perception</p><p className="mt-2 text-xs font-semibold text-slate-700">{event.task_profile.object_type} · {event.task_profile.severity}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-500"><MapPin size={12} />{event.camera_id}<span className="mapping-pulse">→</span>{event.location.map_id}</p></div><div className="border border-emerald-200 bg-emerald-50/40 p-3"><p className="section-kicker">After · verification</p><p className="mt-2 text-xs font-semibold text-emerald-800">{event.verification?.result ?? "PENDING"}</p><p className="mt-1 text-[11px] text-emerald-700">{event.verification?.reason ?? "等待验收结果"}</p></div></div>; }
function TaskProfile({ event }: { event: WorkflowEvent }) { const profile = event.task_profile; return <Card><CardHeader><p className="section-kicker">Task profile</p><h3 className="mt-1 text-sm font-semibold">清洁任务</h3></CardHeader><CardContent className="grid grid-cols-2 gap-x-4 gap-y-3 p-5 pt-4 text-xs"><ProfileCell label="对象" value={profile.object_type} /><ProfileCell label="污染形态" value={profile.pollution_form} /><ProfileCell label="严重度" value={profile.severity} /><ProfileCell label="地面" value={profile.surface} /><div className="col-span-2"><p className="text-[11px] text-slate-400">Required capabilities</p><div className="mt-1 flex flex-wrap gap-1">{profile.required_capabilities.map((item) => <span key={item} className="rounded-sm bg-slate-100 px-1.5 py-0.5 text-[11px] text-slate-600">{item}</span>)}</div></div></CardContent></Card>; }
function ProfileCell({ label, value }: { label:string; value:string }) { return <div><p className="text-[11px] text-slate-400">{label}</p><p className="mt-1 font-medium text-slate-700">{value}</p></div>; }
function AssignmentPanel({ event, selectedCandidate, onSelect }: { event: WorkflowEvent; selectedCandidate?: AssignmentCandidate; onSelect: (candidate: AssignmentCandidate) => void }) { const decision = event.assignment_decision; if (!decision) return null; const fallback = decision.status === "HUMAN_FALLBACK"; return <Card><CardHeader><p className="section-kicker">Assignment decision</p><h3 className="mt-1 flex items-center gap-2 text-sm font-semibold">{fallback ? <UserRound size={15} className="text-amber-700" /> : <ClipboardCheck size={15} className="text-emerald-700" />}{fallback ? "Human Fallback" : `Why ${decision.selected_robot_name}?`}</h3></CardHeader><CardContent className="p-5 pt-4"><p className="mb-3 text-xs leading-5 text-slate-600">{decision.reason}</p><div className="space-y-2">{decision.candidates.map((candidate) => <button key={candidate.robot_id} onClick={() => onSelect(candidate)} className={`w-full rounded-sm border p-3 text-left transition-colors ${selectedCandidate?.robot_id === candidate.robot_id ? "border-slate-700 bg-slate-50" : "border-slate-200 hover:border-slate-300"}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-800">{candidate.robot_name}</span><span className={`text-xs font-semibold ${candidate.eligible ? "text-emerald-700" : "text-slate-400"}`}>{candidate.eligible ? `${candidate.final_score}` : "Filtered"}</span></div><p className="mt-1 text-[11px] text-slate-500">{candidate.eligible ? "点击查看评分维度" : candidate.reject_reasons.join(" · ")}</p></button>)}</div>{selectedCandidate?.eligible && <div className="mt-4 border-t border-slate-100 pt-3"><p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-slate-400">Score components / 100</p><div className="grid grid-cols-2 gap-x-4 gap-y-1.5">{Object.entries(selectedCandidate.score_components).map(([key, value]) => <div key={key} className="flex items-center justify-between text-[11px]"><span className="text-slate-500">{key.split("_").join(" ")}</span><span className="font-mono text-slate-700">{value}</span></div>)}</div></div>}{fallback && event.human_fallback && <p className="mt-4 flex items-center gap-2 border-t border-slate-100 pt-3 text-xs text-amber-800"><CheckCircle2 size={14} />Mock 工单：{event.human_fallback.work_order_id}</p>}</CardContent></Card>; }
