import { Bot, CheckCircle2, CircleAlert, Eye, Route, ShieldCheck, UsersRound } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import type { OperationsWorkOrder } from "@/types/operations";
import type { DemoAsset } from "@/types/workbench";
import { DetectionFrame } from "@/components/operations/DetectionFrame";

export function WorkOrderDetail({ workOrder }: { workOrder: OperationsWorkOrder | null }) {
  if (!workOrder) return <aside className="border border-slate-200 bg-white p-5"><p className="section-kicker">Selected work order</p><h3 className="mt-1 text-base font-semibold">尚未选择工单</h3><p className="mt-3 text-xs leading-5 text-slate-500">左侧选择一个 Scenario 或上传受控清洁前图。创建后，这里会展示 AI、位置、能力校验、调度原因、路线和验收状态。</p></aside>;
  const human = workOrder.verification_pending; const decision = workOrder.assignment_decision; const before = assetFor(workOrder, "before"); const after = assetFor(workOrder, "after");
  return <aside className="border border-slate-200 bg-white"><div className="border-b border-slate-100 p-4"><div className="flex items-start justify-between gap-3"><div><p className="section-kicker">Selected work order</p><h3 className="mt-1 text-base font-semibold">{workOrder.asset_manifest.title}</h3><p className="mt-1 text-[11px] text-slate-500">{workOrder.event.location.building} · {workOrder.event.location.floor} · {workOrder.event.location.zone}</p></div><Badge variant={human ? "outline" : "success"}>{human ? "人工待处理" : workOrder.display_state}</Badge></div></div>
    <div className="space-y-4 p-4"><Image asset={before} label="清洁前现场" /><section className="grid grid-cols-2 gap-y-3 border-y border-slate-100 py-3"><Fact label="AI 识别" value={translateObject(workOrder.event.task_profile.object_type)} /><Fact label="AI 置信度" value={`${Math.round(workOrder.initial_ai_result.perception.confidence * 100)}%`} /><Fact label="SLAM 坐标" value={`(${workOrder.event.location.x.toFixed(1)}, ${workOrder.event.location.y.toFixed(1)})`} /><Fact label="任务要求" value={workOrder.event.task_profile.required_capabilities.map(translateCapability).join(" + ")} /></section>
      <section><p className="section-kicker">确定性调度决策</p><p className="mt-1 flex items-center gap-1 text-xs font-semibold text-slate-800"><Bot size={14} />{decision.selected_robot_name ?? "人工工单"}</p><p className="mt-1 text-[11px] leading-5 text-slate-600">{decision.reason}</p>{workOrder.event.navigation_plan && <p className="mt-2 flex gap-1 text-[11px] leading-5 text-slate-600"><Route size={13} className="mt-0.5 shrink-0" />{workOrder.event.navigation_plan.display_path.join(" → ")}</p>}</section>
      <CloudReview review={workOrder.initial_ai_result.cloud_review} />
      {workOrder.multi_view?.triggered && <section className="border-t border-slate-100 pt-3"><p className="section-kicker">多视角研判</p><p className="mt-1 flex items-center gap-1 text-xs font-semibold text-slate-700"><Eye size={13} />{workOrder.multi_view.selected_cameras.map((camera) => camera.camera_id).join(" / ")} · {workOrder.multi_view.decision} · {Math.round(workOrder.multi_view.final_confidence * 100)}%</p></section>}
      {human ? <section className="border border-amber-200 bg-amber-50 p-3"><p className="flex items-center gap-1 text-xs font-semibold text-amber-900"><UsersRound size={14} />Human Fallback 工单已创建</p><p className="mt-1 text-[11px] leading-5 text-amber-800">大型纸箱不进入机器人调度池。没有清洁后照片时，必须等待人工处理及同机位回传验收。</p></section> : <section className="border border-emerald-200 bg-emerald-50/50 p-3"><p className="flex items-center gap-1 text-xs font-semibold text-emerald-900"><ShieldCheck size={14} />固定摄像头自动验收</p>{after && <Image asset={after} label="清洁后验收图" compact />}<p className="mt-2 text-[11px] text-emerald-800">{workOrder.display_state === "CLOSED" ? <><CheckCircle2 size={12} className="mr-1 inline" />验收通过，原污染物未检出。</> : "回放完成后将展示清洁后图和验收结果。"}</p></section>}</div>
  </aside>;
}

export function AuditTimeline({ workOrder }: { workOrder: OperationsWorkOrder | null }) {
  if (!workOrder) return <section className="border border-slate-200 bg-white p-4"><p className="section-kicker">Workflow audit</p><p className="mt-1 text-sm text-slate-500">创建工单后显示可审计业务状态。</p></section>;
  return <section className="border border-slate-200 bg-white p-4"><div className="flex items-end justify-between"><div><p className="section-kicker">Workflow audit</p><h3 className="mt-1 text-base font-semibold">业务状态与执行审计</h3></div><Badge variant="outline">{workOrder.audit_transitions.length} 条记录</Badge></div><ol className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{workOrder.audit_transitions.map((transition) => <li key={transition.id} className={`border p-2.5 ${transition.state === workOrder.display_state ? "border-slate-800 bg-slate-900 text-white" : "border-slate-100 bg-slate-50"}`}><p className={`text-[10px] font-bold tracking-[0.1em] ${transition.state === workOrder.display_state ? "text-slate-300" : "text-slate-500"}`}>{transition.state}</p><p className={`mt-1 text-[11px] leading-4 ${transition.state === workOrder.display_state ? "text-white" : "text-slate-700"}`}>{transitionMessage(transition.detail)}</p></li>)}</ol></section>;
}

function Image({ asset, label, compact = false }: { asset?: DemoAsset; label: string; compact?: boolean }) { return <div className="mt-3 overflow-hidden border border-slate-200 bg-slate-50"><DetectionFrame asset={asset} label={label} compact={compact} /></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold leading-5 text-slate-700">{value}</p></div>; }
function assetFor(order: OperationsWorkOrder, role: DemoAsset["role"]) { return order.asset_manifest.assets.find((asset) => asset.role === role); }
function translateObject(value: string) { return ({ small_litter: "室外纸巾", beverage_spill: "奶茶液体污渍", aluminum_can: "室内易拉罐", large_cardboard_box: "大型纸箱" } as Record<string, string>)[value] ?? value; }
function translateCapability(value: string) { return ({ outdoor: "室外", dry_debris: "干垃圾", wet_cleaning: "湿洗", strong_suction: "强吸力", scrubbing: "刷洗", light_cleaning: "轻度清洁", large_object_pickup: "大件拾取" } as Record<string, string>)[value] ?? value; }
function transitionMessage(detail: Record<string, unknown>) { return typeof detail.message === "string" ? detail.message : typeof detail.reason === "string" ? detail.reason : "已记录此步骤。"; }
function CloudReview({ review }: { review: OperationsWorkOrder["initial_ai_result"]["cloud_review"] }) { if (!review) return null; if (review.status === "NOT_CONFIGURED") return <section className="border-t border-slate-100 pt-3"><p className="section-kicker">云端复核</p><p className="mt-1 text-[11px] leading-5 text-slate-500">未配置 DashScope API Key；当前仅运行本地受控回放。</p></section>; if (review.status === "FAILED") return <section className="border border-rose-200 bg-rose-50 p-3"><p className="text-xs font-semibold text-rose-800">云端复核调用失败</p><p className="mt-1 text-[11px] leading-5 text-rose-700">{review.reason}</p></section>; return <section className="border border-emerald-200 bg-emerald-50/50 p-3"><p className="section-kicker">云端 Qwen-VL 复核</p><p className="mt-1 text-xs font-semibold text-emerald-900">{review.business_class} · {Math.round((review.confidence ?? 0) * 100)}% · {review.need_clean ? "需要清洁" : "无需清洁"}</p><p className="mt-1 text-[11px] leading-5 text-emerald-800">{review.summary}</p></section>; }
