import { useEffect, useState } from "react";
import { ChevronRight, MapPin, ScanLine } from "lucide-react";

import { fetchMapping, fetchRoute } from "@/api/spatial";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { Camera, MappingResult, Route, SpatialOverview } from "@/types/spatial";

export function SpatialControlPanel({ overview, selectedCamera }: { overview: SpatialOverview; selectedCamera?: Camera }) {
  const [start, setStart] = useState("B_1F"); const [target, setTarget] = useState("A_1F"); const [route, setRoute] = useState<Route>(); const [routeError, setRouteError] = useState("");
  const [u, setU] = useState(500); const [v, setV] = useState(400); const [mapping, setMapping] = useState<MappingResult>(); const [mappingError, setMappingError] = useState("");
  const camera = selectedCamera ?? overview.cameras.find((item) => item.camera_id === "CAM-A1-01");
  useEffect(() => { void runRoute("B_1F", "A_1F"); }, []);
  useEffect(() => { if (camera?.calibration_points.length) void runMapping(camera.camera_id); else { setMapping(undefined); setMappingError(camera ? "此摄像头在 Phase 2 未配置四点标定。" : ""); } }, [camera?.camera_id]);
  async function runRoute(nextStart = start, nextTarget = target) { setRouteError(""); try { setRoute(await fetchRoute(nextStart, nextTarget)); } catch (error) { setRouteError(error instanceof Error ? error.message : "无法计算路线"); } }
  async function runMapping(cameraId = camera?.camera_id) { if (!cameraId) return; setMappingError(""); try { setMapping(await fetchMapping(cameraId, u, v)); } catch (error) { setMapping(undefined); setMappingError(error instanceof Error ? error.message : "无法映射"); } }
  return <div className="space-y-5">
    <Card><CardHeader><p className="section-kicker">Global route</p><h2 className="mt-1 text-base font-semibold">全园区路径</h2></CardHeader><CardContent className="p-5 pt-4"><div className="grid grid-cols-2 gap-2"><select aria-label="起点地图" value={start} onChange={(event) => setStart(event.target.value)} className="h-9 rounded-sm border border-slate-200 bg-white px-2 text-xs">{overview.maps.filter((map) => map.map_id !== "OUTDOOR").map((map) => <option key={map.map_id} value={map.map_id}>{map.label}</option>)}</select><select aria-label="终点地图" value={target} onChange={(event) => setTarget(event.target.value)} className="h-9 rounded-sm border border-slate-200 bg-white px-2 text-xs">{overview.maps.filter((map) => map.map_id !== "OUTDOOR").map((map) => <option key={map.map_id} value={map.map_id}>{map.label}</option>)}</select></div><button onClick={() => void runRoute()} className="mt-2 w-full rounded-sm bg-slate-900 py-2 text-xs font-medium text-white hover:bg-slate-700">计算 Dijkstra 路线</button><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => { setStart("A_2F"); setTarget("A_B1"); void runRoute("A_2F", "A_B1"); }} className="text-[11px] text-slate-500 hover:text-slate-900">测试 1 · Robot B · A 2F → B1</button><button onClick={() => { setStart("B_1F"); setTarget("A_1F"); void runRoute("B_1F", "A_1F"); }} className="text-[11px] text-slate-500 hover:text-slate-900">测试 2 · Robot C · B 1F → A 1F</button></div>{routeError ? <p className="mt-3 text-xs text-rose-600">{routeError}</p> : route && <div className="mt-4 border-t border-slate-100 pt-3"><div className="flex flex-wrap items-center gap-1 text-xs leading-5 text-slate-700">{route.display_path.map((step, index) => <span key={`${step}-${index}`} className="flex items-center gap-1"><span className="rounded-sm bg-slate-100 px-1.5 py-0.5">{step}</span>{index < route.display_path.length - 1 && <ChevronRight size={13} className="text-slate-400" />}</span>)}</div><p className="mt-3 text-[11px] text-slate-500">确定性 Dijkstra · 连接成本 {route.total_cost}</p></div>}</CardContent></Card>
    <Card><CardHeader><p className="section-kicker">Camera calibration</p><h2 className="mt-1 text-base font-semibold">Pixel → SLAM</h2></CardHeader><CardContent className="p-5 pt-4">{camera && <div className="mb-3 flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-800">{camera.camera_id}</p><p className="mt-0.5 text-[11px] text-slate-500">{camera.building} · {camera.floor} · {camera.zone}</p></div><Badge variant={camera.calibration_points.length ? "success" : "outline"}>{camera.calibration_points.length ? "4-point" : "No calibration"}</Badge></div>}<div className="grid grid-cols-2 gap-2"><label className="text-[11px] text-slate-500">Pixel U<input aria-label="Pixel U" type="number" value={u} onChange={(event) => setU(Number(event.target.value))} className="mt-1 h-8 w-full rounded-sm border border-slate-200 px-2 text-xs" /></label><label className="text-[11px] text-slate-500">Pixel V<input aria-label="Pixel V" type="number" value={v} onChange={(event) => setV(Number(event.target.value))} className="mt-1 h-8 w-full rounded-sm border border-slate-200 px-2 text-xs" /></label></div><button disabled={!camera?.calibration_points.length} onClick={() => void runMapping()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-sm bg-slate-900 py-2 text-xs font-medium text-white enabled:hover:bg-slate-700 disabled:cursor-not-allowed disabled:bg-slate-300"><ScanLine size={14} />执行四点映射</button>{mappingError && <p className="mt-3 text-xs text-amber-700">{mappingError}</p>}{mapping && <div className="mt-4 border-t border-slate-100 pt-3"><div className="flex items-center gap-2 text-xs text-slate-700"><MapPin size={14} className="text-teal-700" />{mapping.location.building} · {mapping.location.floor} · {mapping.location.zone}</div><p className="mt-2 font-mono text-sm font-semibold text-slate-800">SLAM ({mapping.location.x.toFixed(3)}, {mapping.location.y.toFixed(3)})</p><p className="mt-1 text-[11px] text-slate-500">Pixel ({mapping.pixel.u}, {mapping.pixel.v}) · 可复现计算</p></div>}</CardContent></Card>
  </div>;
}
