"""Demo-only confidence and execution bounds for Multi-view Perception."""

INITIAL_CONFIRM_THRESHOLD = 0.85
GRAY_ZONE_MIN = 0.55
GRAY_ZONE_MAX = 0.85
MULTIVIEW_CONFIRM_THRESHOLD = 0.85
MULTIVIEW_REVIEW_THRESHOLD = 0.60
MAX_ADDITIONAL_CAMERAS = 2
MAX_AGENT_ITERATIONS = 2
