from __future__ import annotations

from typing import Protocol


class RobotAdapter(Protocol):
    def get_status(self, robot_id: str) -> dict: ...
    def get_position(self, robot_id: str) -> dict: ...
    def assign_task(self, robot_id: str, task_id: str) -> dict: ...
    def navigate(self, robot_id: str, navigation_plan: dict) -> dict: ...
    def start_cleaning(self, robot_id: str, task_profile: dict) -> dict: ...
    def cancel_task(self, robot_id: str, task_id: str) -> dict: ...
