import { ChevronDown, ChevronUp, Clock3, RotateCcw, ShieldCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cameras, stageCopy } from "./data";
import type { ActiveEvent, PrototypeState } from "./types";

function timestamp(startedAt: string, offset: number) { return new Date(new Date(startedAt).getTime() + offset * 1100).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" }); }

function Evidence({ event, state }: { event: ActiveEvent; state: PrototypeState }) {
  if (state === "EDGE_DETECTED") return <div className="mt-2 border border-slate-200 bg-slate-50 p-2 text-[11px] text-slate-600"><p className="font-medium text-slate-800">单视角目标定位</p><p className="mt-1">{event.scenario.category} · {event.scenario.confidence}% · 已保留原始像素坐标</p></div>;
  if (state === "MULTI_VIEW") return <div className="mt-2 grid grid-cols-3 gap-1.5">{["CAM-A1-01", "CAM-A1-02", "CAM-A1-04"].map((id) => <div key={id} className="border border-amber-200 bg-amber-50 p-1"><img src={cameras[id].image} className="aspect-[4/3] w-full object-contain" alt={id} /><p className="mt-1 text-[9px] font-medium text-amber-800">{id} · {Math.round((cameras[id].overlay?.[0].confidence ?? 0) * 100)}%</p></div>)}</div>;
  if (state === "CLOUD_REVIEW") return <div className="mt-2 border border-slate-200 bg-white p-2 text-[11px]"><div className="flex items-center justify-between"><span className="font-medium text-slate-800">云端综合研判</span><span className="font-semibold text-emerald-700">需要清洁 · {event.scenario.qwenConfidence}%</span></div><p className="mt-1 leading-5 text-slate-600">{event.scenario.qwenSummary}</p></div>;
  if (state === "ROBOT_ASSIGNED" && event.scenario.robot) return <div className="mt-2 border border-slate-200 bg-slate-50 p-2 text-[11px] text-slate-600"><p className="font-medium text-slate-800">{event.scenario.robot} 已接单</p><p className="mt-1">{event.scenario.route} · 电量充足 · 能力匹配</p></div>;
  if (state === "VERIFYING" || state === "CLOSED") return <div className="mt-2 grid grid-cols-2 gap-2"><img className="aspect-[4/3] w-full border border-slate-200 object-contain" src={cameras[event.scenario.cameraId].image} alt="清洁前" />{event.scenario.afterImage && <img className="aspect-[4/3] w-full border border-emerald-200 object-contain" src={event.scenario.afterImage} alt="清洁后" />}<p className="col-span-2 flex items-center gap-1 text-[11px] font-medium text-emerald-700"><ShieldCheck size={14} />AI 验收：PASS，现场已恢复可用状态</p></div>;
  return null;
}

export function EventDetailPanel({ event }: { event: ActiveEvent | null }) {
  const [follow, setFollow] = useState(true);
  const [techOpen, setTechOpen] = useState(false);
  const bodyRef = useRef<HTMLDivElement>(null);
  const stage = event ? event.scenario.steps[event.stageIndex] : "IDLE";
  useEffect(() => { if (follow && bodyRef.current) bodyRef.current.scrollTop = bodyRef.current.scrollHeight; }, [event, follow]);
  useEffect(() => { setFollow(true); setTechOpen(false); }, [event?.startedAt]);
  const handleScroll = () => { const panel = bodyRef.current; if (panel && panel.scrollHeight - panel.scrollTop - panel.clientHeight > 28) setFollow(false); };
  if (!event) return <aside className="relative flex h-full min-h-0 flex-col border border-slate-200 bg-white"><PanelHeader /><div className="flex flex-1 flex-col items-center justify-center px-8 text-center"><div className="mb-3 h-9 w-9 border border-slate-300 bg-slate-50" /><p className="text-sm font-medium text-slate-700">当前没有事件</p><p className="mt-2 text-xs leading-5 text-slate-500">园区摄像头持续监测中。可从监控卡片右上角的演示控制触发一项业务事件。</p></div></aside>;
  const history = event.scenario.steps.slice(0, event.stageIndex + 1);
  return <aside className="relative flex h-full min-h-0 flex-col border border-slate-200 bg-white"><PanelHeader /><div ref={bodyRef} onScroll={handleScroll} className="min-h-0 flex-1 overflow-y-auto p-4 pr-3"><div className="border-b border-slate-100 pb-3"><p className="text-sm font-semibold text-slate-900">{event.scenario.eventTitle}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] text-slate-600">{event.scenario.cameraId}</span><span className="border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] text-slate-600">{event.scenario.category}</span><span className="border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] text-slate-600">{event.scenario.confidence}%</span></div></div>
    <div className="mt-4 space-y-0.5">{history.map((item, index) => { const copy = stageCopy[item]; const isCurrent = index === event.stageIndex; const fallback = item === "HUMAN_FALLBACK"; return <div key={`${item}-${index}`} className={`relative border-l pl-4 ${isCurrent ? "border-slate-900" : "border-slate-200"}`}><span className={`absolute -left-[5px] top-1.5 h-2 w-2 rounded-full ${fallback ? "bg-amber-500" : isCurrent ? "bg-slate-900" : "bg-emerald-500"}`} /><div className="pb-3"><div className="flex gap-2"><p className={`text-xs ${isCurrent ? "font-semibold text-slate-900" : "font-medium text-slate-700"}`}>{copy.title}</p><span className="ml-auto whitespace-nowrap text-[10px] text-slate-400">{timestamp(event.startedAt, index)}</span></div><p className="mt-1 text-[11px] leading-4 text-slate-500">{copy.detail}</p>{(isCurrent || item === "EDGE_DETECTED" || item === "MULTI_VIEW" || item === "CLOUD_REVIEW" || item === "ROBOT_ASSIGNED" || item === "VERIFYING" || item === "CLOSED") && <Evidence event={event} state={item} />}</div></div>; })}</div>
    <div className="mt-2 border-t border-slate-100 pt-3"><button onClick={() => setTechOpen((value) => !value)} className="flex w-full items-center justify-between text-left text-[11px] font-medium text-slate-600">技术细节（原始坐标、JSON、API、耗时）{techOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button>{techOpen && <pre className="mt-2 overflow-x-auto border border-slate-200 bg-slate-50 p-2 text-[9px] leading-4 text-slate-600">{JSON.stringify({ event: event.scenario.id, camera: event.scenario.cameraId, bbox: cameras[event.scenario.cameraId].overlay?.map((o) => o.bbox), edge_score: event.scenario.confidence, cloud_score: event.scenario.qwenConfidence, cloud_mode: "prototype_stub_no_api", spatial: "camera_to_slam_shared_convention" }, null, 2)}</pre>}</div>
  </div>{!follow && stage !== "CLOSED" && stage !== "HUMAN_FALLBACK" && <button onClick={() => { setFollow(true); if (bodyRef.current) bodyRef.current.scrollTop = bodyRef.current.scrollHeight; }} className="absolute bottom-3 right-3 flex items-center gap-1 border border-slate-300 bg-white px-2 py-1.5 text-[11px] font-medium text-slate-700 shadow-sm"><RotateCcw size={12} />回到当前进度</button>}</aside>;
}

function PanelHeader() { return <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><p className="text-sm font-semibold text-slate-900">最近事件处置详情</p><p className="mt-0.5 text-[10px] text-slate-500">仅展示当前或最近闭环事件</p></div><Clock3 size={16} className="text-slate-400" /></div>; }
