import { ChevronDown, ChevronUp, Clock3, RotateCcw, ShieldCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { CameraViewport } from "./CameraViewport";
import { cameras, stageCopy } from "./data";
import type { ActiveEvent, PrototypeState } from "./types";

function timestamp(startedAt: string, offset: number) { return new Date(new Date(startedAt).getTime() + offset * 1100).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit" }); }

function MultiViewEvidence({ event }: { event: ActiveEvent }) {
  const selected = (event.liveResult?.multi_view as { selected_cameras?: Array<{ camera_id: string; reason?: string }> } | undefined)?.selected_cameras;
  const cameraIds = selected?.map((item) => item.camera_id).filter((id) => cameras[id]) ?? ["CAM-A1-01", "CAM-A1-02", "CAM-A1-04"];
  const [primary = "CAM-A1-01", ...additional] = cameraIds;
  const render = (id: string, compact = false) => <div key={id} className="border border-amber-200 bg-amber-50 p-1"><CameraViewport camera={cameras[id]} showDetections compact={compact} /><p className="mt-1 text-[9px] font-medium text-amber-800">{id} · {Math.round((cameras[id].overlay?.[0].confidence ?? 0) * 100)}%</p></div>;
  return <div className="mt-2"><p className="mb-1 text-[10px] font-medium text-slate-600">多视角证据（主视角 + 最多 2 路补充）</p><div className="grid gap-1.5">{render(primary)}<div className="grid grid-cols-2 gap-1.5">{additional.slice(0, 2).map((id) => render(id, true))}</div></div><p className="mt-1.5 text-[10px] leading-4 text-slate-500">3 路单视角证据均未达到自动处置条件；Multi-view Agent 已完成证据汇聚，正在提交云端综合研判。</p></div>;
}

function CapabilitySummary({ event }: { event: ActiveEvent }) {
  const selected = String((event.liveResult?.assignment_decision as Record<string, unknown> | undefined)?.selected_robot_name ?? event.scenario.robot ?? "");
  const candidates = [
    { name: "Robot A", label: "室外清扫 A", location: "园区东侧", battery: "82%", capability: "纸屑 / 落叶 / 小型垃圾", note: selected === "Robot A" ? "最佳匹配" : "液体洗地不支持" },
    { name: "Robot B", label: "重载洗地 B", location: "A栋1F", battery: "71%", capability: "液体污渍 / 强洗地", note: selected === "Robot B" ? "最佳匹配" : "场景能力非最优" },
    { name: "Robot C", label: "室内清洁 C", location: "B栋1F", battery: "89%", capability: "易拉罐 / 纸屑 / 小型垃圾", note: selected === "Robot C" ? "最佳匹配" : "可达但能力非最优" },
  ];
  return <div className="mt-2 border border-slate-200 bg-slate-50 p-2 text-[10px]"><p className="font-medium text-slate-800">机器人能力匹配</p><div className="mt-1.5 divide-y divide-slate-200">{candidates.map((candidate) => <div key={candidate.name} className="py-1.5"><div className="flex items-center justify-between gap-2"><span className="font-medium text-slate-700">{candidate.label}</span><span className={candidate.name === selected ? "font-semibold text-emerald-700" : "text-slate-500"}>{candidate.note}</span></div><p className="mt-0.5 text-slate-500">{candidate.location} · 电量 {candidate.battery} · {candidate.capability}</p></div>)}</div><p className="mt-1.5 border-t border-slate-200 pt-1.5 text-slate-600">最终选择：<span className="font-semibold text-slate-800">{selected}</span>。选择依据由既有能力匹配、可达性和电量约束共同决定。</p></div>;
}

function Evidence({ event, state }: { event: ActiveEvent; state: PrototypeState }) {
  if (state === "EDGE_DETECTED") return <div className="mt-2 border border-slate-200 bg-slate-50 p-2 text-[11px] text-slate-600"><p className="mb-1.5 font-medium text-slate-800">单视角目标定位</p><CameraViewport camera={cameras[event.scenario.cameraId]} showDetections compact /><p className="mt-1.5">{event.scenario.category} · {event.scenario.confidence}% · 已保留原始像素坐标</p></div>;
  if (state === "MULTI_VIEW") return <MultiViewEvidence event={event} />;
  if (state === "CLOUD_REVIEW") { const review = event.liveResult?.qwen_review as Record<string, unknown> | undefined; const status = event.liveResult?.status; const imageCount = event.scenario.id === "liquid" ? 3 : 1; if (event.cloudLoading) return <div className="mt-2 border border-slate-200 bg-white p-2 text-[11px] text-slate-600"><p className="font-medium text-slate-800">云端综合研判</p>{event.scenario.id === "liquid" && <MultiViewEvidence event={event} />}<p className="mt-1">正在分析 {imageCount} 路现场图像，等待千问视觉大模型返回…</p></div>; if (!review) return <div className="mt-2 border border-amber-200 bg-amber-50 p-2 text-[11px] text-amber-800">云端综合研判未完成：{String(event.liveResult?.reason ?? "请人工复核")}</div>; return <div className="mt-2 border border-slate-200 bg-white p-2 text-[11px]"><div className="flex items-center justify-between"><span className="font-medium text-slate-800">云端综合研判 · 千问视觉大模型</span><span className={status === "HUMAN_REVIEW" ? "font-semibold text-amber-700" : "font-semibold text-emerald-700"}>{String(review.need_clean ? "需要清洁" : "不需清洁")} · {Math.round(Number(review.decision_confidence ?? 0) * 100)}%</span></div>{event.scenario.id === "liquid" && <MultiViewEvidence event={event} />}<p className="mt-1 text-slate-600">综合结论：{String(review.event_type ?? "unknown")} · 污染程度：{String(review.severity ?? "")}</p><p className="mt-1 text-slate-600">地面材质：{String(review.surface_type ?? "未明确")} · 建议：{String(review.next_action ?? "human_review")}</p>{Array.isArray(review.interference_factors) && review.interference_factors.length > 0 && <p className="mt-1 text-slate-600">干扰因素：{review.interference_factors.map(String).join("、")}</p>}<p className="mt-1 leading-5 text-slate-600">研判依据：{String(review.evidence_summary ?? "")}</p><p className="mt-1 text-[10px] text-slate-400">真实 API 耗时：{Number(review.elapsed_ms ?? 0) / 1000}s · 已上传 {Number(review.image_count ?? imageCount)} 张现场图像</p></div>; }
  if (state === "ROBOT_ASSIGNED" && event.scenario.robot) return <><CapabilitySummary event={event} /><div className="mt-2 border border-slate-200 bg-slate-50 p-2 text-[11px] text-slate-600"><p className="font-medium text-slate-800">{event.scenario.robot} 已接单</p><p className="mt-1">{event.scenario.route} · 电量充足 · 能力匹配</p></div></>;
  if (state === "VERIFYING") { const verification = event.liveResult?.verification as Record<string, unknown> | undefined; return <div className="mt-2 grid grid-cols-2 gap-2"><div><p className="mb-1 text-[9px] text-slate-500">清洁前</p><img className="aspect-[4/3] w-full border border-slate-200 object-contain" src={cameras[event.scenario.cameraId].image} alt="清洁前" /></div>{event.scenario.afterImage && <div><p className="mb-1 text-[9px] text-slate-500">清洁后</p><img className="aspect-[4/3] w-full border border-emerald-200 object-contain" src={event.scenario.afterImage} alt="清洁后" /></div>}<p className="col-span-2 flex items-center gap-1 text-[11px] font-medium text-emerald-700"><ShieldCheck size={14} />{verification?.provider === "Stable Replay" ? "受控回放验收通过" : `真实 AI 验收：${verification?.verification_pass ? "通过" : "待人工复核"}`} · {Math.round(Number(verification?.confidence ?? 0) * 100)}%</p></div>; }
  if (state === "CLOSED") return <div className="mt-2 border border-emerald-200 bg-emerald-50 p-2 text-[11px] text-emerald-800"><p className="flex items-center gap-1 font-semibold"><ShieldCheck size={14} />事件已闭环</p><p className="mt-1.5">闭环时间：{timestamp(event.startedAt, event.scenario.steps.length - 1)}</p><p className="mt-1">自主处置：{event.scenario.robot ?? "人工处置"} · 总耗时：{Math.max(1, event.scenario.steps.length - 1) * 11} 秒</p><p className="mt-1">完整事件记录已保存。</p></div>;
  return null;
}

export function EventDetailPanel({ event }: { event: ActiveEvent | null }) {
  const [follow, setFollow] = useState(true);
  const [techOpen, setTechOpen] = useState(false);
  const bodyRef = useRef<HTMLDivElement>(null);
  const stage = event ? event.scenario.steps[event.stageIndex] : "IDLE";
  useEffect(() => { if (follow && bodyRef.current) bodyRef.current.scrollTop = bodyRef.current.scrollHeight; }, [event, follow]);
  useEffect(() => { setFollow(true); setTechOpen(false); }, [event?.startedAt]);
  const handleScroll = () => { const panel = bodyRef.current; if (panel && panel.scrollHeight - panel.scrollTop - panel.clientHeight > 28) setFollow(false); };
  if (!event) return <aside className="relative flex h-full min-h-0 flex-col border border-slate-200 bg-white"><PanelHeader /><div className="flex flex-1 flex-col items-center justify-center px-8 text-center"><div className="mb-3 h-9 w-9 border border-slate-300 bg-slate-50" /><p className="text-sm font-medium text-slate-700">当前没有事件</p><p className="mt-2 text-xs leading-5 text-slate-500">园区摄像头持续监测中。可从监控卡片右上角的演示控制触发一项业务事件。</p></div></aside>;
  const timeline = event.scenario.steps;
  return <aside className="relative flex h-full min-h-0 flex-col border border-slate-200 bg-white"><PanelHeader /><div ref={bodyRef} onScroll={handleScroll} className="min-h-0 flex-1 overflow-y-auto p-4 pr-3"><div className="sticky top-0 z-10 -mt-4 border-b border-slate-100 bg-white pb-3 pt-4"><p className="text-sm font-semibold text-slate-900">{event.scenario.eventTitle}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] text-slate-600">{event.scenario.cameraId}</span><span className="border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] text-slate-600">{event.scenario.category}</span><span className="border border-slate-200 bg-slate-50 px-1.5 py-1 text-[10px] text-slate-600">{event.scenario.confidence}%</span></div></div>
    <div className="mt-4 space-y-0.5">{timeline.map((item, index) => { const copy = stageCopy[item]; const isCurrent = index === event.stageIndex; const isFuture = index > event.stageIndex; const fallback = item === "HUMAN_FALLBACK"; return <div key={`${item}-${index}`} className={`relative border-l pl-4 ${isCurrent ? "border-slate-900" : isFuture ? "border-slate-100" : "border-slate-200"}`}><span className={`absolute -left-[5px] top-1.5 h-2 w-2 rounded-full ${fallback && !isFuture ? "bg-amber-500" : isFuture ? "bg-slate-200" : isCurrent ? "bg-slate-900" : "bg-emerald-500"}`} /><div className="pb-3"><div className="flex gap-2"><p className={`text-xs ${isFuture ? "text-slate-400" : isCurrent ? "font-semibold text-slate-900" : "font-medium text-slate-700"}`}>{copy.title}</p><span className="ml-auto whitespace-nowrap text-[10px] text-slate-400">{isFuture ? "等待" : timestamp(event.startedAt, index)}</span></div><p className={`mt-1 text-[11px] leading-4 ${isFuture ? "text-slate-400" : "text-slate-500"}`}>{copy.detail}</p>{!isFuture && (isCurrent || item === "EDGE_DETECTED" || item === "MULTI_VIEW" || item === "CLOUD_REVIEW" || item === "ROBOT_ASSIGNED" || item === "VERIFYING" || item === "CLOSED") && <Evidence event={event} state={item} />}</div></div>; })}</div>
    <div className="mt-2 border-t border-slate-100 pt-3"><button onClick={() => setTechOpen((value) => !value)} className="flex w-full items-center justify-between text-left text-[11px] font-medium text-slate-600">技术细节（原始坐标、JSON、API、耗时）{techOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button>{techOpen && <pre className="mt-2 overflow-x-auto border border-slate-200 bg-slate-50 p-2 text-[9px] leading-4 text-slate-600">{JSON.stringify({ event: event.scenario.id, camera: event.scenario.cameraId, bbox: cameras[event.scenario.cameraId].overlay?.map((o) => o.bbox), edge_score: event.scenario.confidence, cloud_provider: event.liveResult?.qwen_review ? "DashScope Qwen-VL" : "pending", cloud_result: event.liveResult?.qwen_review ?? null, spatial: "camera_to_slam_shared_convention" }, null, 2)}</pre>}</div>
  </div>{!follow && stage !== "CLOSED" && stage !== "HUMAN_FALLBACK" && <button onClick={() => { setFollow(true); if (bodyRef.current) bodyRef.current.scrollTop = bodyRef.current.scrollHeight; }} className="absolute bottom-3 right-3 flex items-center gap-1 border border-slate-300 bg-white px-2 py-1.5 text-[11px] font-medium text-slate-700 shadow-sm"><RotateCcw size={12} />回到当前进度</button>}</aside>;
}

function PanelHeader() { return <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><p className="text-sm font-semibold text-slate-900">最近事件处置详情</p><p className="mt-0.5 text-[10px] text-slate-500">仅展示当前或最近闭环事件</p></div><Clock3 size={16} className="text-slate-400" /></div>; }
