import { useState } from "react";
import { AlertTriangle, CheckCircle2, LoaderCircle, Play, Radio, ScanSearch } from "lucide-react";

import { runMultiViewScenario02 } from "@/api/multiview";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { MultiViewScenarioEvent, MultiViewTrace } from "@/types/multiview";

export function MultiViewAgentPanel() {
  const [event, setEvent] = useState<MultiViewScenarioEvent>();
  const [running, setRunning] = useState(false);
  const [error, setError] = useState("");
  async function runScenario() { setRunning(true); setError(""); try { setEvent(await runMultiViewScenario02()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Multi-view Scenario 02 运行失败"); } finally { setRunning(false); } }
  return <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,0.8fr)]"><Card><CardHeader className="flex flex-col gap-3 p-5 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="section-kicker">Multi-view Perception Agent</p><h2 className="mt-1 text-base font-semibold">Scenario 02 · 灰区视觉研判</h2><p className="mt-1 text-xs leading-5 text-slate-500">仅在初始置信度处于灰区时触发；工具边界固定为 Coverage、Frame Fetch 与 VLM。</p></div><Badge variant="outline"><Radio size={11} className="mr-1" />{event ? event.multi_view_trace.decision : "等待演示"}</Badge></CardHeader><CardContent className="p-5 pt-1"><div className="flex flex-col gap-2 border-y border-slate-100 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-600">A 栋 1F 疑似奶茶污渍 · 初始 confidence <span className="font-mono font-semibold">0.67</span></p><button onClick={() => void runScenario()} disabled={running} className="flex h-9 items-center justify-center gap-2 rounded-sm bg-slate-900 px-4 text-xs font-medium text-white hover:bg-slate-700 disabled:bg-slate-300">{running ? <LoaderCircle size={14} className="animate-spin" /> : <Play size={14} />}{running ? "研判中" : "运行 Scenario 02"}</button></div>{error && <p role="alert" className="mt-4 flex gap-2 border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800"><AlertTriangle size={15} />{error}</p>}{event ? <Trace trace={event.multi_view_trace} /> : <div className="flex min-h-[230px] items-center justify-center border-b border-dashed border-slate-200 text-sm text-slate-400">运行稳定 Scenario 02，查看受限工具调用与可审计证据。</div>}</CardContent></Card><BoundaryCard trace={event?.multi_view_trace} /></section>;
}

function Trace({ trace }: { trace: MultiViewTrace }) { return <div className="mt-4"><div className="grid grid-cols-2 gap-3 border-b border-slate-100 pb-4"><Fact label="Final confidence" value={`${Math.round(trace.final_confidence * 100)}%`} /><Fact label="Decision" value={trace.decision ?? "未触发"} /></div><div className="mt-4"><p className="section-kicker">Selected cameras</p><div className="mt-2 flex flex-wrap gap-2">{trace.selected_cameras.map((camera) => <span key={camera.camera_id} className="border border-slate-200 bg-slate-50 px-2 py-1 text-[11px] text-slate-700">{camera.camera_id} · {camera.zone}</span>)}</div></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><p className="section-kicker">Tool calls</p><div className="mt-2 space-y-2">{trace.tool_calls.map((call, index) => <div key={`${call.tool}-${index}`} className="flex items-center gap-2 border-l-2 border-slate-300 py-1 pl-3 text-xs text-slate-600"><ScanSearch size={13} className="text-slate-400" /><span className="font-medium text-slate-700">{call.tool}</span>{call.camera_id && <span className="font-mono text-[10px] text-slate-400">{call.camera_id}</span>}</div>)}</div></div><div><p className="section-kicker">Evidence</p><div className="mt-2 space-y-2">{trace.evidence.map((item) => <div key={item.frame_id} className="border border-slate-200 px-3 py-2 text-[11px]"><div className="flex justify-between"><span className="font-medium text-slate-700">{item.camera_id}</span><span className="font-mono text-slate-400">{Math.round(item.confidence * 100)}%</span></div><p className="mt-1 leading-4 text-slate-500">{item.observation}</p></div>)}</div></div></div></div>; }
function BoundaryCard({ trace }: { trace?: MultiViewTrace }) { return <Card><CardHeader><p className="section-kicker">Agent boundary</p><h3 className="mt-1 text-sm font-semibold">有限工具 · 无隐藏推理</h3></CardHeader><CardContent className="space-y-3 p-5 pt-3"><div className="divide-y divide-slate-100 border-y border-slate-100">{[["Camera Coverage Tool", "复用 Phase 2 覆盖多边形"], ["Frame Fetch Tool", "提取近同步画面证据"], ["VLM Tool", "输出结构化视觉结论"]].map(([name, detail]) => <div key={name} className="flex items-center justify-between gap-4 py-3"><span className="text-xs font-medium text-slate-700">{name}</span><span className="text-right text-[11px] text-slate-400">{detail}</span></div>)}</div><p className="text-xs leading-5 text-slate-500">上限：额外摄像头 {trace?.limits.max_additional_cameras ?? 2} 个、Agent iteration {trace?.limits.max_agent_iterations ?? 2} 次。界面只呈现 Tool Calls、Evidence、Selected Cameras、Final Confidence 与 Decision。</p>{trace && <p className="flex items-center gap-2 border-t border-slate-100 pt-3 text-xs text-emerald-700"><CheckCircle2 size={14} />{trace.decision === "CONFIRM" ? "已确认并交回既有工作流。" : "已输出最终视觉决策。"}</p>}</CardContent></Card>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="section-kicker">{label}</p><p className="mt-1 truncate text-xs font-semibold text-slate-700">{value}</p></div>; }
